/* Looking prompts for the untimed tour. Names and sources remain in E. */
export const TOUR_NOTES = [
  'Begin at Meru, the central mountain. Look at its four coloured faces, terraces and summit. Everything else in the offering is arranged in relation to this centre.',
  'Find Pūrvavideha in the east. Its semicircular outline distinguishes it from the other three continents. East stays fixed in the world even when you turn the camera.',
  'Jambudvīpa is the southern continent. Notice its tapering outline. Its rose-apple tree is separate from the wish-fulfilling tree offered at point 15.',
  'The western continent, Aparagodānīya, has a round outline. Its treasure, offered later, is the wish-fulfilling cow.',
  'The northern continent, Uttarakuru, is square. Its treasure is grain that grows without being sown.',
  'Deha is the first of the two smaller continents associated with Pūrvavideha. The next eight heaps name the companions of the four main continents.',
  'Videha completes the eastern pair. Compare the two small landforms with their larger neighbouring continent.',
  'Cāmara is the first companion of the southern continent. Each of the southern companions is a distinct offering point.',
  'Aparacāmara completes the southern pair. Notice the two smaller landforms beside Jambudvīpa.',
  'Śāthā is the first of the western pair, beside Aparagodānīya.',
  'Uttaramantriṇa completes the western pair. The recitation names each smaller continent separately.',
  'Kurava is the first companion of Uttarakuru in the north. This is the final pair of smaller continents.',
  'Kaurava completes the eight subcontinents. The central mountain and all twelve continents have now been offered.',
  'The eastern treasure is a mountain of precious substances. Look at the varied mineral surfaces in the painting. The illustration is deliberately enlarged for study.',
  'The southern treasure is the wish-fulfilling tree. Hanging jewels express abundance. Keep it distinct from the jambu, or rose-apple, tree shown with Jambudvīpa.',
  'The western treasure is the wish-fulfilling cow. The painting gives the animal a natural body and a jewelled collar.',
  'The northern treasure is the unsown harvest. Look at the ripe heads of grain, imagining nourishment available without ploughing, sowing or tending.',
  'The precious wheel begins the seven emblems of a universal monarch. The text describes a thousand-spoked golden wheel. The painting abbreviates its spokes for readability.',
  'The precious jewel is shown as a luminous blue gem. The painted facets and radiance are an artistic rendering of the jewel described in the offering traditions.',
  'The queen is distinguished by her royal dress and ornaments. The lotus and the precise arrangement of her silks are choices in this modern illustration.',
  'The minister administers the monarch’s realm. His treasure casket suggests its resources; the costume and hand-held object are illustrative choices.',
  'Look at the white elephant’s forehead ornament, harness, tusks and single trunk. The natural anatomy replaces the earlier schematic figure.',
  'The precious horse is white and richly adorned. Its flowing mane and lifted foreleg suggest the extraordinary speed associated with this offering.',
  'The general completes the seven royal emblems. Lamellar armour, sword and shield make his role legible. These costume details are an illustrative interpretation.',
  'The vase of great treasure follows the seven emblems. This painting uses a jewel finial. Vase closures and ornament vary in traditional representations.',
  'Lāsyā offers beauty and graceful bearing. Here her posture and empty hands carry the meaning, without giving her the mirror of a separate visible-form offering.',
  'Mālā offers garlands. Follow the loop between her hands, distinct from the bowl of flowers offered at point 30.',
  'Gītā offers song. Here the figure sings with open hands. Larger offering groups also include separate goddesses playing musical instruments.',
  'Nṛtyā offers dance. Look at the lifted leg, the two arm gestures and the movement of the drapery.',
  'Puṣpā offers flowers. The blossoms are presented in a shallow bowl, distinct from Mālā’s hanging garland.',
  'Dhūpā offers incense. The censer and rising threads of smoke make the fragrant offering visible.',
  'Ālokā offers light. Look for the small flame above the butter lamp and the hands supporting its base.',
  'Gandhā offers scented water. Here it is presented in a conch shell, one vessel used in traditional offering imagery. She completes the eight goddesses.',
  'The sun is offered at the eastern point in this diagram. This painted disc is separate from the sun’s moving position in the cosmological world view.',
  'The moon is offered at the western point in this diagram. Compare its cool white disc with the warm solar disc.',
  'The parasol occupies the southern point. Notice the white canopy, hanging ornaments, shaft and jewel at its summit.',
  'The victory banner completes the thirty-seven heaps. Look at its cylindrical tiers and hanging silks. The recitation then offers the completed world system as a whole.'
];
