// Generated by scripts/build-places.cjs from the repository city list.
export const PLACES = Object.freeze([
  {
    "name": "New York, NY, United States",
    "latitude": 40.7128,
    "longitude": -74.006,
    "zone": "America/New_York"
  },
  {
    "name": "Los Angeles, CA, United States",
    "latitude": 34.0522,
    "longitude": -118.2437,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Chicago, IL, United States",
    "latitude": 41.8781,
    "longitude": -87.6298,
    "zone": "America/Chicago"
  },
  {
    "name": "Houston, TX, United States",
    "latitude": 29.7604,
    "longitude": -95.3698,
    "zone": "America/Chicago"
  },
  {
    "name": "Phoenix, AZ, United States",
    "latitude": 33.4484,
    "longitude": -112.074,
    "zone": "America/Phoenix"
  },
  {
    "name": "Philadelphia, PA, United States",
    "latitude": 39.9526,
    "longitude": -75.1652,
    "zone": "America/New_York"
  },
  {
    "name": "San Antonio, TX, United States",
    "latitude": 29.4241,
    "longitude": -98.4936,
    "zone": "America/Chicago"
  },
  {
    "name": "San Diego, CA, United States",
    "latitude": 32.7157,
    "longitude": -117.1611,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Dallas, TX, United States",
    "latitude": 32.7767,
    "longitude": -96.797,
    "zone": "America/Chicago"
  },
  {
    "name": "San Jose, CA, United States",
    "latitude": 37.3382,
    "longitude": -121.8863,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Austin, TX, United States",
    "latitude": 30.2672,
    "longitude": -97.7431,
    "zone": "America/Chicago"
  },
  {
    "name": "Jacksonville, FL, United States",
    "latitude": 30.3322,
    "longitude": -81.6557,
    "zone": "America/New_York"
  },
  {
    "name": "Fort Worth, TX, United States",
    "latitude": 32.7555,
    "longitude": -97.3308,
    "zone": "America/Chicago"
  },
  {
    "name": "Columbus, OH, United States",
    "latitude": 39.9612,
    "longitude": -82.9988,
    "zone": "America/New_York"
  },
  {
    "name": "Indianapolis, IN, United States",
    "latitude": 39.7684,
    "longitude": -86.1581,
    "zone": "America/Indiana/Indianapolis"
  },
  {
    "name": "Charlotte, NC, United States",
    "latitude": 35.2271,
    "longitude": -80.8431,
    "zone": "America/New_York"
  },
  {
    "name": "San Francisco, CA, United States",
    "latitude": 37.7749,
    "longitude": -122.4194,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Seattle, WA, United States",
    "latitude": 47.6062,
    "longitude": -122.3321,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Denver, CO, United States",
    "latitude": 39.7392,
    "longitude": -104.9903,
    "zone": "America/Denver"
  },
  {
    "name": "Washington, D.C., United States",
    "latitude": 38.9072,
    "longitude": -77.0369,
    "zone": "America/New_York"
  },
  {
    "name": "Boston, MA, United States",
    "latitude": 42.3601,
    "longitude": -71.0589,
    "zone": "America/New_York"
  },
  {
    "name": "El Paso, TX, United States",
    "latitude": 31.7619,
    "longitude": -106.485,
    "zone": "America/Denver"
  },
  {
    "name": "Nashville, TN, United States",
    "latitude": 36.1627,
    "longitude": -86.7816,
    "zone": "America/Chicago"
  },
  {
    "name": "Detroit, MI, United States",
    "latitude": 42.3314,
    "longitude": -83.0458,
    "zone": "America/Detroit"
  },
  {
    "name": "Oklahoma City, OK, United States",
    "latitude": 35.4676,
    "longitude": -97.5164,
    "zone": "America/Chicago"
  },
  {
    "name": "Portland, OR, United States",
    "latitude": 45.5152,
    "longitude": -122.6784,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Las Vegas, NV, United States",
    "latitude": 36.1699,
    "longitude": -115.1398,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Memphis, TN, United States",
    "latitude": 35.1495,
    "longitude": -90.049,
    "zone": "America/Chicago"
  },
  {
    "name": "Louisville, KY, United States",
    "latitude": 38.2527,
    "longitude": -85.7585,
    "zone": "America/Kentucky/Louisville"
  },
  {
    "name": "Baltimore, MD, United States",
    "latitude": 39.2904,
    "longitude": -76.6122,
    "zone": "America/New_York"
  },
  {
    "name": "Milwaukee, WI, United States",
    "latitude": 43.0389,
    "longitude": -87.9065,
    "zone": "America/Chicago"
  },
  {
    "name": "Albuquerque, NM, United States",
    "latitude": 35.0844,
    "longitude": -106.6504,
    "zone": "America/Denver"
  },
  {
    "name": "Tucson, AZ, United States",
    "latitude": 32.2226,
    "longitude": -110.9747,
    "zone": "America/Phoenix"
  },
  {
    "name": "Fresno, CA, United States",
    "latitude": 36.7378,
    "longitude": -119.7871,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Sacramento, CA, United States",
    "latitude": 38.5816,
    "longitude": -121.4944,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Kansas City, MO, United States",
    "latitude": 39.0997,
    "longitude": -94.5786,
    "zone": "America/Chicago"
  },
  {
    "name": "Mesa, AZ, United States",
    "latitude": 33.4152,
    "longitude": -111.8315,
    "zone": "America/Phoenix"
  },
  {
    "name": "Atlanta, GA, United States",
    "latitude": 33.749,
    "longitude": -84.388,
    "zone": "America/New_York"
  },
  {
    "name": "Omaha, NE, United States",
    "latitude": 41.2565,
    "longitude": -95.9345,
    "zone": "America/Chicago"
  },
  {
    "name": "Colorado Springs, CO, United States",
    "latitude": 38.8339,
    "longitude": -104.8214,
    "zone": "America/Denver"
  },
  {
    "name": "Raleigh, NC, United States",
    "latitude": 35.7796,
    "longitude": -78.6382,
    "zone": "America/New_York"
  },
  {
    "name": "Miami, FL, United States",
    "latitude": 25.7617,
    "longitude": -80.1918,
    "zone": "America/New_York"
  },
  {
    "name": "Oakland, CA, United States",
    "latitude": 37.8044,
    "longitude": -122.2712,
    "zone": "America/Los_Angeles"
  },
  {
    "name": "Minneapolis, MN, United States",
    "latitude": 44.9778,
    "longitude": -93.265,
    "zone": "America/Chicago"
  },
  {
    "name": "Tulsa, OK, United States",
    "latitude": 36.154,
    "longitude": -95.9928,
    "zone": "America/Chicago"
  },
  {
    "name": "Tampa, FL, United States",
    "latitude": 27.9506,
    "longitude": -82.4572,
    "zone": "America/New_York"
  },
  {
    "name": "New Orleans, LA, United States",
    "latitude": 29.9511,
    "longitude": -90.0715,
    "zone": "America/Chicago"
  },
  {
    "name": "Honolulu, HI, United States",
    "latitude": 21.3099,
    "longitude": -157.8581,
    "zone": "Pacific/Honolulu"
  },
  {
    "name": "Anchorage, AK, United States",
    "latitude": 61.2181,
    "longitude": -149.9003,
    "zone": "America/Anchorage"
  },
  {
    "name": "Salt Lake City, UT, United States",
    "latitude": 40.7608,
    "longitude": -111.891,
    "zone": "America/Denver"
  },
  {
    "name": "Orlando, FL, United States",
    "latitude": 28.5383,
    "longitude": -81.3792,
    "zone": "America/New_York"
  },
  {
    "name": "Warsaw, Poland",
    "latitude": 52.2297,
    "longitude": 21.0122,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Kraków, Poland",
    "latitude": 50.0647,
    "longitude": 19.945,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Łódź, Poland",
    "latitude": 51.7592,
    "longitude": 19.4558,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Wrocław, Poland",
    "latitude": 51.1079,
    "longitude": 17.0385,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Poznań, Poland",
    "latitude": 52.4064,
    "longitude": 16.9252,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Gdańsk, Poland",
    "latitude": 54.352,
    "longitude": 18.6466,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Szczecin, Poland",
    "latitude": 53.4285,
    "longitude": 14.5528,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Bydgoszcz, Poland",
    "latitude": 53.1235,
    "longitude": 18.0084,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Lublin, Poland",
    "latitude": 51.2465,
    "longitude": 22.5684,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Białystok, Poland",
    "latitude": 53.1325,
    "longitude": 23.1688,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Katowice, Poland",
    "latitude": 50.2649,
    "longitude": 19.0238,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Gdynia, Poland",
    "latitude": 54.5189,
    "longitude": 18.5305,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Częstochowa, Poland",
    "latitude": 50.7964,
    "longitude": 19.1241,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Radom, Poland",
    "latitude": 51.4027,
    "longitude": 21.1471,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Toruń, Poland",
    "latitude": 53.0138,
    "longitude": 18.5984,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Sosnowiec, Poland",
    "latitude": 50.2863,
    "longitude": 19.1039,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Kielce, Poland",
    "latitude": 50.8661,
    "longitude": 20.6286,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Rzeszów, Poland",
    "latitude": 50.0412,
    "longitude": 21.9991,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Gliwice, Poland",
    "latitude": 50.2976,
    "longitude": 18.6766,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Zabrze, Poland",
    "latitude": 50.3249,
    "longitude": 18.7857,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Olsztyn, Poland",
    "latitude": 53.7784,
    "longitude": 20.4801,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Bielsko-Biała, Poland",
    "latitude": 49.8225,
    "longitude": 19.0444,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Bytom, Poland",
    "latitude": 50.348,
    "longitude": 18.915,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Zielona Góra, Poland",
    "latitude": 51.9356,
    "longitude": 15.5062,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Rybnik, Poland",
    "latitude": 50.0971,
    "longitude": 18.5418,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Ruda Śląska, Poland",
    "latitude": 50.2584,
    "longitude": 18.8555,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Opole, Poland",
    "latitude": 50.6669,
    "longitude": 17.9236,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Tychy, Poland",
    "latitude": 50.1362,
    "longitude": 18.9797,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Gorzów Wielkopolski, Poland",
    "latitude": 52.7368,
    "longitude": 15.2288,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Elbląg, Poland",
    "latitude": 54.1561,
    "longitude": 19.4045,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Płock, Poland",
    "latitude": 52.5463,
    "longitude": 19.7065,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Wałbrzych, Poland",
    "latitude": 50.7714,
    "longitude": 16.2756,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Włocławek, Poland",
    "latitude": 52.6481,
    "longitude": 19.0678,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Tarnów, Poland",
    "latitude": 50.0125,
    "longitude": 20.9859,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Chorzów, Poland",
    "latitude": 50.2975,
    "longitude": 18.9546,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Koszalin, Poland",
    "latitude": 54.1944,
    "longitude": 16.1722,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Kalisz, Poland",
    "latitude": 51.7611,
    "longitude": 18.091,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Legnica, Poland",
    "latitude": 51.207,
    "longitude": 16.1553,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Zakopane, Poland",
    "latitude": 49.2992,
    "longitude": 19.9496,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "Sopot, Poland",
    "latitude": 54.4416,
    "longitude": 18.5601,
    "zone": "Europe/Warsaw"
  },
  {
    "name": "London, UK",
    "latitude": 51.5074,
    "longitude": -0.1278,
    "zone": "Europe/London"
  },
  {
    "name": "Birmingham, UK",
    "latitude": 52.4862,
    "longitude": -1.8904,
    "zone": "Europe/London"
  },
  {
    "name": "Manchester, UK",
    "latitude": 53.483,
    "longitude": -2.2446,
    "zone": "Europe/London"
  },
  {
    "name": "Edinburgh, UK",
    "latitude": 55.9533,
    "longitude": -3.1883,
    "zone": "Europe/London"
  },
  {
    "name": "Glasgow, UK",
    "latitude": 55.8642,
    "longitude": -4.2518,
    "zone": "Europe/London"
  },
  {
    "name": "Paris, France",
    "latitude": 48.8566,
    "longitude": 2.3522,
    "zone": "Europe/Paris"
  },
  {
    "name": "Marseille, France",
    "latitude": 43.2965,
    "longitude": 5.3698,
    "zone": "Europe/Paris"
  },
  {
    "name": "Lyon, France",
    "latitude": 45.764,
    "longitude": 4.8357,
    "zone": "Europe/Paris"
  },
  {
    "name": "Toulouse, France",
    "latitude": 43.6047,
    "longitude": 1.4442,
    "zone": "Europe/Paris"
  },
  {
    "name": "Berlin, Germany",
    "latitude": 52.52,
    "longitude": 13.405,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Munich, Germany",
    "latitude": 48.1351,
    "longitude": 11.582,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Frankfurt, Germany",
    "latitude": 50.1109,
    "longitude": 8.6821,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Hamburg, Germany",
    "latitude": 53.5511,
    "longitude": 9.9937,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Cologne, Germany",
    "latitude": 50.9375,
    "longitude": 6.9603,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Stuttgart, Germany",
    "latitude": 48.7758,
    "longitude": 9.1829,
    "zone": "Europe/Berlin"
  },
  {
    "name": "Madrid, Spain",
    "latitude": 40.4168,
    "longitude": -3.7038,
    "zone": "Europe/Madrid"
  },
  {
    "name": "Barcelona, Spain",
    "latitude": 41.3874,
    "longitude": 2.1686,
    "zone": "Europe/Madrid"
  },
  {
    "name": "Valencia, Spain",
    "latitude": 39.4699,
    "longitude": -0.3763,
    "zone": "Europe/Madrid"
  },
  {
    "name": "Seville, Spain",
    "latitude": 37.3891,
    "longitude": -5.9845,
    "zone": "Europe/Madrid"
  },
  {
    "name": "Rome, Italy",
    "latitude": 41.9028,
    "longitude": 12.4964,
    "zone": "Europe/Rome"
  },
  {
    "name": "Milan, Italy",
    "latitude": 45.4642,
    "longitude": 9.19,
    "zone": "Europe/Rome"
  },
  {
    "name": "Naples, Italy",
    "latitude": 40.8518,
    "longitude": 14.2681,
    "zone": "Europe/Rome"
  },
  {
    "name": "Turin, Italy",
    "latitude": 45.0703,
    "longitude": 7.6869,
    "zone": "Europe/Rome"
  },
  {
    "name": "Venice, Italy",
    "latitude": 45.4408,
    "longitude": 12.3155,
    "zone": "Europe/Rome"
  },
  {
    "name": "Florence, Italy",
    "latitude": 43.7696,
    "longitude": 11.2558,
    "zone": "Europe/Rome"
  },
  {
    "name": "Amsterdam, Netherlands",
    "latitude": 52.3676,
    "longitude": 4.9041,
    "zone": "Europe/Amsterdam"
  },
  {
    "name": "Rotterdam, Netherlands",
    "latitude": 51.9225,
    "longitude": 4.4792,
    "zone": "Europe/Amsterdam"
  },
  {
    "name": "The Hague, Netherlands",
    "latitude": 52.0705,
    "longitude": 4.3007,
    "zone": "Europe/Amsterdam"
  },
  {
    "name": "Brussels, Belgium",
    "latitude": 50.8503,
    "longitude": 4.3517,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Antwerp, Belgium",
    "latitude": 51.2194,
    "longitude": 4.4025,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Ghent (Gent / Gand), Belgium",
    "latitude": 51.05,
    "longitude": 3.7167,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Bruges (Brugge), Belgium",
    "latitude": 51.2089,
    "longitude": 3.2242,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Liège (Luik), Belgium",
    "latitude": 50.6337,
    "longitude": 5.5675,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Charleroi, Belgium",
    "latitude": 50.4114,
    "longitude": 4.4445,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Namur (Namen), Belgium",
    "latitude": 50.4669,
    "longitude": 4.8675,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Leuven (Louvain), Belgium",
    "latitude": 50.8796,
    "longitude": 4.7009,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Mons (Bergen), Belgium",
    "latitude": 50.4541,
    "longitude": 3.9523,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Mechelen (Malines), Belgium",
    "latitude": 51.0257,
    "longitude": 4.4776,
    "zone": "Europe/Brussels"
  },
  {
    "name": "La Louvière, Belgium",
    "latitude": 50.4866,
    "longitude": 4.1879,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Kortrijk (Courtrai), Belgium",
    "latitude": 50.828,
    "longitude": 3.2649,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Hasselt, Belgium",
    "latitude": 50.9311,
    "longitude": 5.3378,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Genk, Belgium",
    "latitude": 50.965,
    "longitude": 5.5008,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Ieper (Ypres), Belgium",
    "latitude": 50.8511,
    "longitude": 2.8857,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Roeselare (Roulers), Belgium",
    "latitude": 50.9465,
    "longitude": 3.1227,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Ostend (Oostende), Belgium",
    "latitude": 51.2155,
    "longitude": 2.927,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Wavre (Waver), Belgium",
    "latitude": 50.7172,
    "longitude": 4.6014,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Waterloo, Belgium",
    "latitude": 50.7147,
    "longitude": 4.3991,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Verviers, Belgium",
    "latitude": 50.5891,
    "longitude": 5.8624,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Tournai (Doornik), Belgium",
    "latitude": 50.6072,
    "longitude": 3.3893,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Tongeren (Tongres), Belgium",
    "latitude": 50.7805,
    "longitude": 5.4648,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Sint-Truiden (Saint-Trond), Belgium",
    "latitude": 50.8168,
    "longitude": 5.1865,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Anderlecht, Belgium",
    "latitude": 50.8362,
    "longitude": 4.3145,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Ixelles (Elsene), Belgium",
    "latitude": 50.8333,
    "longitude": 4.3667,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Schaerbeek (Schaarbeek), Belgium",
    "latitude": 50.8694,
    "longitude": 4.3774,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Uccle (Ukkel), Belgium",
    "latitude": 50.8022,
    "longitude": 4.3394,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Mol, Belgium",
    "latitude": 51.1919,
    "longitude": 5.1166,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Maaseik, Belgium",
    "latitude": 51.098,
    "longitude": 5.7838,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Lommel, Belgium",
    "latitude": 51.2307,
    "longitude": 5.3135,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Geel, Belgium",
    "latitude": 51.1656,
    "longitude": 4.9892,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Beringen, Belgium",
    "latitude": 51.0495,
    "longitude": 5.2261,
    "zone": "Europe/Brussels"
  },
  {
    "name": "Vienna, Austria",
    "latitude": 48.2082,
    "longitude": 16.3738,
    "zone": "Europe/Vienna"
  },
  {
    "name": "Salzburg, Austria",
    "latitude": 47.8095,
    "longitude": 13.055,
    "zone": "Europe/Vienna"
  },
  {
    "name": "Zurich, Switzerland",
    "latitude": 47.3769,
    "longitude": 8.5417,
    "zone": "Europe/Zurich"
  },
  {
    "name": "Geneva, Switzerland",
    "latitude": 46.2044,
    "longitude": 6.1432,
    "zone": "Europe/Zurich"
  },
  {
    "name": "Basel, Switzerland",
    "latitude": 47.5596,
    "longitude": 7.5886,
    "zone": "Europe/Zurich"
  },
  {
    "name": "Prague, Czechia",
    "latitude": 50.0755,
    "longitude": 14.4378,
    "zone": "Europe/Prague"
  },
  {
    "name": "Brno, Czechia",
    "latitude": 49.1951,
    "longitude": 16.6068,
    "zone": "Europe/Prague"
  },
  {
    "name": "Bratislava, Slovakia",
    "latitude": 48.1486,
    "longitude": 17.1077,
    "zone": "Europe/Bratislava"
  },
  {
    "name": "Budapest, Hungary",
    "latitude": 47.4979,
    "longitude": 19.0402,
    "zone": "Europe/Budapest"
  },
  {
    "name": "Copenhagen, Denmark",
    "latitude": 55.6761,
    "longitude": 12.5683,
    "zone": "Europe/Copenhagen"
  },
  {
    "name": "Stockholm, Sweden",
    "latitude": 59.3293,
    "longitude": 18.0686,
    "zone": "Europe/Stockholm"
  },
  {
    "name": "Gothenburg, Sweden",
    "latitude": 57.7089,
    "longitude": 11.9746,
    "zone": "Europe/Stockholm"
  },
  {
    "name": "Oslo, Norway",
    "latitude": 59.9139,
    "longitude": 10.7522,
    "zone": "Europe/Oslo"
  },
  {
    "name": "Bergen, Norway",
    "latitude": 60.3929,
    "longitude": 5.322,
    "zone": "Europe/Oslo"
  },
  {
    "name": "Helsinki, Finland",
    "latitude": 60.1699,
    "longitude": 24.9384,
    "zone": "Europe/Helsinki"
  },
  {
    "name": "Dublin, Ireland",
    "latitude": 53.3498,
    "longitude": -6.2603,
    "zone": "Europe/Dublin"
  },
  {
    "name": "Lisbon, Portugal",
    "latitude": 38.7223,
    "longitude": -9.1393,
    "zone": "Europe/Lisbon"
  },
  {
    "name": "Porto, Portugal",
    "latitude": 41.1579,
    "longitude": -8.6291,
    "zone": "Europe/Lisbon"
  },
  {
    "name": "Athens, Greece",
    "latitude": 37.9838,
    "longitude": 23.7275,
    "zone": "Europe/Athens"
  },
  {
    "name": "Thessaloniki, Greece",
    "latitude": 40.6401,
    "longitude": 22.9444,
    "zone": "Europe/Athens"
  },
  {
    "name": "Bucharest, Romania",
    "latitude": 44.4268,
    "longitude": 26.1025,
    "zone": "Europe/Bucharest"
  },
  {
    "name": "Cluj-Napoca, Romania",
    "latitude": 46.7712,
    "longitude": 23.6236,
    "zone": "Europe/Bucharest"
  },
  {
    "name": "Sofia, Bulgaria",
    "latitude": 42.6977,
    "longitude": 23.3219,
    "zone": "Europe/Sofia"
  },
  {
    "name": "Zagreb, Croatia",
    "latitude": 45.815,
    "longitude": 15.9819,
    "zone": "Europe/Zagreb"
  },
  {
    "name": "Split, Croatia",
    "latitude": 43.5081,
    "longitude": 16.4402,
    "zone": "Europe/Zagreb"
  },
  {
    "name": "Belgrade, Serbia",
    "latitude": 44.8125,
    "longitude": 20.4612,
    "zone": "Europe/Belgrade"
  },
  {
    "name": "Kyiv, Ukraine",
    "latitude": 50.4501,
    "longitude": 30.5234,
    "zone": "Europe/Kyiv"
  },
  {
    "name": "Lviv, Ukraine",
    "latitude": 49.8397,
    "longitude": 24.0297,
    "zone": "Europe/Kyiv"
  },
  {
    "name": "Riga, Latvia",
    "latitude": 56.9496,
    "longitude": 24.1052,
    "zone": "Europe/Riga"
  },
  {
    "name": "Vilnius, Lithuania",
    "latitude": 54.6872,
    "longitude": 25.2797,
    "zone": "Europe/Vilnius"
  },
  {
    "name": "Tallinn, Estonia",
    "latitude": 59.437,
    "longitude": 24.7536,
    "zone": "Europe/Tallinn"
  },
  {
    "name": "Reykjavik, Iceland",
    "latitude": 64.1466,
    "longitude": -21.9426,
    "zone": "Atlantic/Reykjavik"
  },
  {
    "name": "Istanbul, Turkey (Europe/Asia)",
    "latitude": 41.0082,
    "longitude": 28.9784,
    "zone": "Europe/Istanbul"
  },
  {
    "name": "New Delhi, India",
    "latitude": 28.6139,
    "longitude": 77.209,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Mumbai, India",
    "latitude": 19.076,
    "longitude": 72.8777,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Bengaluru, India",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Chennai, India",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kolkata, India",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Hyderabad, India",
    "latitude": 17.385,
    "longitude": 78.4867,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Pune, India",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Ahmedabad, India",
    "latitude": 23.0225,
    "longitude": 72.5714,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Jaipur, India",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Lucknow, India",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kanpur, India",
    "latitude": 26.4499,
    "longitude": 80.3319,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Nagpur, India",
    "latitude": 21.1458,
    "longitude": 79.0882,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Indore, India",
    "latitude": 22.7196,
    "longitude": 75.8577,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Thane, India",
    "latitude": 19.2183,
    "longitude": 72.9781,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Bhopal, India",
    "latitude": 23.2599,
    "longitude": 77.4126,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Visakhapatnam, India",
    "latitude": 17.6868,
    "longitude": 83.2185,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Pimpri-Chinchwad, India",
    "latitude": 18.6298,
    "longitude": 73.7997,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Patna, India",
    "latitude": 25.5941,
    "longitude": 85.1376,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Vadodara, India",
    "latitude": 22.3072,
    "longitude": 73.1812,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Ghaziabad, India",
    "latitude": 28.6692,
    "longitude": 77.4538,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Ludhiana, India",
    "latitude": 30.901,
    "longitude": 75.8523,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Agra, India",
    "latitude": 27.1767,
    "longitude": 78.0081,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Nashik, India",
    "latitude": 20.011,
    "longitude": 73.7903,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Faridabad, India",
    "latitude": 28.4089,
    "longitude": 77.3178,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Meerut, India",
    "latitude": 28.9845,
    "longitude": 77.7064,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Rajkot, India",
    "latitude": 22.3039,
    "longitude": 70.8022,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kalyan-Dombivli, India",
    "latitude": 19.2403,
    "longitude": 73.1305,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Vasai-Virar, India",
    "latitude": 19.3919,
    "longitude": 72.8397,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Varanasi, India",
    "latitude": 25.3176,
    "longitude": 82.9739,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Srinagar, India",
    "latitude": 34.0837,
    "longitude": 74.7973,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Aurangabad, India",
    "latitude": 19.8762,
    "longitude": 75.3433,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Dhanbad, India",
    "latitude": 23.7957,
    "longitude": 86.4304,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Amritsar, India",
    "latitude": 31.634,
    "longitude": 74.8723,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Navi Mumbai, India",
    "latitude": 19.033,
    "longitude": 73.0297,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Allahabad (Prayagraj), India",
    "latitude": 25.4358,
    "longitude": 81.8463,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Howrah, India",
    "latitude": 22.5958,
    "longitude": 88.2636,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Ranchi, India",
    "latitude": 23.3441,
    "longitude": 85.3096,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Gwalior, India",
    "latitude": 26.2183,
    "longitude": 78.1828,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Jabalpur, India",
    "latitude": 23.1815,
    "longitude": 79.9864,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Coimbatore, India",
    "latitude": 11.0168,
    "longitude": 76.9558,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Vijayawada, India",
    "latitude": 16.5062,
    "longitude": 80.648,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Jodhpur, India",
    "latitude": 26.2389,
    "longitude": 73.0243,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Madurai, India",
    "latitude": 9.9252,
    "longitude": 78.1198,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Raipur, India",
    "latitude": 21.2514,
    "longitude": 81.6296,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kota, India",
    "latitude": 25.2138,
    "longitude": 75.8648,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Guwahati, India",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Chandigarh, India",
    "latitude": 30.7333,
    "longitude": 76.7794,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Thiruvananthapuram, India",
    "latitude": 8.5241,
    "longitude": 76.9366,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Mysore, India",
    "latitude": 12.2958,
    "longitude": 76.6394,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Bhubaneswar, India",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kochi, India",
    "latitude": 9.9312,
    "longitude": 76.2673,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Dehradun, India",
    "latitude": 30.3165,
    "longitude": 78.0322,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Udaipur, India",
    "latitude": 24.5854,
    "longitude": 73.7125,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Shimla, India",
    "latitude": 31.1048,
    "longitude": 77.1734,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Leh, India",
    "latitude": 34.1526,
    "longitude": 77.5771,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Darjeeling, India",
    "latitude": 27.041,
    "longitude": 88.2663,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Panaji (Goa), India",
    "latitude": 15.4909,
    "longitude": 73.8278,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Puducherry, India",
    "latitude": 11.9416,
    "longitude": 79.8083,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Rishikesh, India",
    "latitude": 30.0869,
    "longitude": 78.2676,
    "zone": "Asia/Kolkata"
  },
  {
    "name": "Kathmandu, Nepal",
    "latitude": 27.7172,
    "longitude": 85.324,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Pokhara, Nepal",
    "latitude": 28.2096,
    "longitude": 83.9856,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Lalitpur (Patan), Nepal",
    "latitude": 27.6588,
    "longitude": 85.3247,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Bhaktapur, Nepal",
    "latitude": 27.671,
    "longitude": 85.4298,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Bharatpur (Chitwan), Nepal",
    "latitude": 27.6833,
    "longitude": 84.4333,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Biratnagar, Nepal",
    "latitude": 26.4525,
    "longitude": 87.2718,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Birgunj, Nepal",
    "latitude": 27.0122,
    "longitude": 84.8774,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Janakpur, Nepal",
    "latitude": 26.7288,
    "longitude": 85.925,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Hetauda, Nepal",
    "latitude": 27.4284,
    "longitude": 85.0328,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Dharan, Nepal",
    "latitude": 26.8126,
    "longitude": 87.2796,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Butwal, Nepal",
    "latitude": 27.6866,
    "longitude": 83.4323,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Nepalgunj, Nepal",
    "latitude": 28.05,
    "longitude": 81.6167,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Itahari, Nepal",
    "latitude": 26.6646,
    "longitude": 87.2721,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Dhangadhi, Nepal",
    "latitude": 28.69,
    "longitude": 80.5963,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Siddharthanagar, Nepal",
    "latitude": 27.5065,
    "longitude": 83.4379,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Lumbini, Nepal",
    "latitude": 27.4833,
    "longitude": 83.2766,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Namche Bazaar, Nepal",
    "latitude": 27.8069,
    "longitude": 86.714,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Tansen, Nepal",
    "latitude": 27.8673,
    "longitude": 83.5467,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Gorkha, Nepal",
    "latitude": 28,
    "longitude": 84.6333,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Dhulikhel, Nepal",
    "latitude": 27.6253,
    "longitude": 85.5561,
    "zone": "Asia/Kathmandu"
  },
  {
    "name": "Thimphu, Bhutan",
    "latitude": 27.4728,
    "longitude": 89.639,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Paro, Bhutan",
    "latitude": 27.4287,
    "longitude": 89.4164,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Phuentsholing, Bhutan",
    "latitude": 26.8523,
    "longitude": 89.3849,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Punakha, Bhutan",
    "latitude": 27.5921,
    "longitude": 89.8797,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Wangdue Phodrang, Bhutan",
    "latitude": 27.4745,
    "longitude": 89.885,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Gelephu, Bhutan",
    "latitude": 26.8621,
    "longitude": 90.4944,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Samdrup Jongkhar, Bhutan",
    "latitude": 26.8,
    "longitude": 91.5,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Jakar (Bumthang), Bhutan",
    "latitude": 27.5624,
    "longitude": 90.7444,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Mongar, Bhutan",
    "latitude": 27.2747,
    "longitude": 91.2396,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Trashigang, Bhutan",
    "latitude": 27.3314,
    "longitude": 91.5545,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Trongsa, Bhutan",
    "latitude": 27.5,
    "longitude": 90.5,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Haa, Bhutan",
    "latitude": 27.3875,
    "longitude": 89.2807,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Damphu (Tsirang), Bhutan",
    "latitude": 27.0167,
    "longitude": 90.1167,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Zhemgang, Bhutan",
    "latitude": 27.2167,
    "longitude": 90.65,
    "zone": "Asia/Thimphu"
  },
  {
    "name": "Taipei, Taiwan",
    "latitude": 25.033,
    "longitude": 121.5654,
    "zone": "Asia/Taipei"
  },
  {
    "name": "New Taipei City, Taiwan",
    "latitude": 25.0112,
    "longitude": 121.4589,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Kaohsiung, Taiwan",
    "latitude": 22.6273,
    "longitude": 120.3014,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Taichung, Taiwan",
    "latitude": 24.1477,
    "longitude": 120.6736,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Tainan, Taiwan",
    "latitude": 22.9997,
    "longitude": 120.227,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Taoyuan, Taiwan",
    "latitude": 24.9936,
    "longitude": 121.301,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Hsinchu, Taiwan",
    "latitude": 24.8138,
    "longitude": 120.9675,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Keelung, Taiwan",
    "latitude": 25.1276,
    "longitude": 121.7392,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Chiayi, Taiwan",
    "latitude": 23.4801,
    "longitude": 120.4491,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Changhua, Taiwan",
    "latitude": 24.0756,
    "longitude": 120.544,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Pingtung, Taiwan",
    "latitude": 22.6687,
    "longitude": 120.4862,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Hualien, Taiwan",
    "latitude": 23.977,
    "longitude": 121.6068,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Taitung, Taiwan",
    "latitude": 22.7583,
    "longitude": 121.1444,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Yilan, Taiwan",
    "latitude": 24.7562,
    "longitude": 121.7516,
    "zone": "Asia/Taipei"
  },
  {
    "name": "Bangkok, Thailand",
    "latitude": 13.7563,
    "longitude": 100.5018,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Chiang Mai, Thailand",
    "latitude": 18.7953,
    "longitude": 98.962,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Phuket, Thailand",
    "latitude": 7.8906,
    "longitude": 98.3981,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Pattaya, Thailand",
    "latitude": 12.9236,
    "longitude": 100.8825,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Nonthaburi, Thailand",
    "latitude": 13.8591,
    "longitude": 100.5217,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Pak Kret, Thailand",
    "latitude": 13.913,
    "longitude": 100.4988,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Hat Yai, Thailand",
    "latitude": 7.0097,
    "longitude": 100.4687,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Nakhon Ratchasima, Thailand",
    "latitude": 14.9799,
    "longitude": 102.0978,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Udon Thani, Thailand",
    "latitude": 17.4138,
    "longitude": 102.7872,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Surat Thani, Thailand",
    "latitude": 9.1382,
    "longitude": 99.3217,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Khon Kaen, Thailand",
    "latitude": 16.4322,
    "longitude": 102.8236,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Ayutthaya, Thailand",
    "latitude": 14.3505,
    "longitude": 100.5583,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Hua Hin, Thailand",
    "latitude": 12.5684,
    "longitude": 99.9577,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Chiang Rai, Thailand",
    "latitude": 19.9105,
    "longitude": 99.8406,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Krabi, Thailand",
    "latitude": 8.0863,
    "longitude": 98.9063,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Koh Samui, Thailand",
    "latitude": 9.512,
    "longitude": 99.0136,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Ubon Ratchathani, Thailand",
    "latitude": 15.2287,
    "longitude": 104.8564,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Phitsanulok, Thailand",
    "latitude": 16.8211,
    "longitude": 100.2659,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Nakhon Si Thammarat, Thailand",
    "latitude": 8.4304,
    "longitude": 99.9631,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Songkhla, Thailand",
    "latitude": 7.1988,
    "longitude": 100.5951,
    "zone": "Asia/Bangkok"
  },
  {
    "name": "Beijing, China",
    "latitude": 39.9042,
    "longitude": 116.4074,
    "zone": "Asia/Shanghai"
  },
  {
    "name": "Shanghai, China",
    "latitude": 31.2304,
    "longitude": 121.4737,
    "zone": "Asia/Shanghai"
  },
  {
    "name": "Guangzhou, China",
    "latitude": 23.1291,
    "longitude": 113.2644,
    "zone": "Asia/Shanghai"
  },
  {
    "name": "Shenzhen, China",
    "latitude": 22.5431,
    "longitude": 114.0579,
    "zone": "Asia/Shanghai"
  },
  {
    "name": "Hong Kong, China",
    "latitude": 22.3193,
    "longitude": 114.1694,
    "zone": "Asia/Hong_Kong"
  },
  {
    "name": "Tokyo, Japan",
    "latitude": 35.6762,
    "longitude": 139.6503,
    "zone": "Asia/Tokyo"
  },
  {
    "name": "Osaka, Japan",
    "latitude": 34.6937,
    "longitude": 135.5023,
    "zone": "Asia/Tokyo"
  },
  {
    "name": "Kyoto, Japan",
    "latitude": 35.0116,
    "longitude": 135.7681,
    "zone": "Asia/Tokyo"
  },
  {
    "name": "Seoul, South Korea",
    "latitude": 37.5665,
    "longitude": 126.978,
    "zone": "Asia/Seoul"
  },
  {
    "name": "Busan, South Korea",
    "latitude": 35.1796,
    "longitude": 129.0756,
    "zone": "Asia/Seoul"
  },
  {
    "name": "Singapore, Singapore",
    "latitude": 1.3521,
    "longitude": 103.8198,
    "zone": "Asia/Singapore"
  },
  {
    "name": "Kuala Lumpur, Malaysia",
    "latitude": 3.139,
    "longitude": 101.6869,
    "zone": "Asia/Kuala_Lumpur"
  },
  {
    "name": "George Town, Malaysia",
    "latitude": 5.4141,
    "longitude": 100.3288,
    "zone": "Asia/Kuala_Lumpur"
  },
  {
    "name": "Jakarta, Indonesia",
    "latitude": -6.2088,
    "longitude": 106.8456,
    "zone": "Asia/Jakarta"
  },
  {
    "name": "Bali (Denpasar), Indonesia",
    "latitude": -8.6705,
    "longitude": 115.2126,
    "zone": "Asia/Makassar"
  },
  {
    "name": "Manila, Philippines",
    "latitude": 14.5995,
    "longitude": 120.9842,
    "zone": "Asia/Manila"
  },
  {
    "name": "Cebu City, Philippines",
    "latitude": 10.3157,
    "longitude": 123.8854,
    "zone": "Asia/Manila"
  },
  {
    "name": "Ho Chi Minh City, Vietnam",
    "latitude": 10.8231,
    "longitude": 106.6297,
    "zone": "Asia/Ho_Chi_Minh"
  },
  {
    "name": "Hanoi, Vietnam",
    "latitude": 21.0285,
    "longitude": 105.8542,
    "zone": "Asia/Ho_Chi_Minh"
  },
  {
    "name": "Dhaka, Bangladesh",
    "latitude": 23.8103,
    "longitude": 90.4125,
    "zone": "Asia/Dhaka"
  },
  {
    "name": "Colombo, Sri Lanka",
    "latitude": 6.9271,
    "longitude": 79.8612,
    "zone": "Asia/Colombo"
  },
  {
    "name": "Dubai, UAE",
    "latitude": 25.2048,
    "longitude": 55.2708,
    "zone": "Asia/Dubai"
  },
  {
    "name": "Abu Dhabi, UAE",
    "latitude": 24.4539,
    "longitude": 54.3773,
    "zone": "Asia/Dubai"
  },
  {
    "name": "Riyadh, Saudi Arabia",
    "latitude": 24.7136,
    "longitude": 46.6753,
    "zone": "Asia/Riyadh"
  },
  {
    "name": "Tel Aviv, Israel",
    "latitude": 32.0853,
    "longitude": 34.7818,
    "zone": "Asia/Jerusalem"
  },
  {
    "name": "Jerusalem, Israel",
    "latitude": 31.7683,
    "longitude": 35.2137,
    "zone": "Asia/Jerusalem"
  },
  {
    "name": "Sydney, Australia",
    "latitude": -33.8688,
    "longitude": 151.2093,
    "zone": "Australia/Sydney"
  },
  {
    "name": "Melbourne, Australia",
    "latitude": -37.8136,
    "longitude": 144.9631,
    "zone": "Australia/Melbourne"
  },
  {
    "name": "Brisbane, Australia",
    "latitude": -27.4698,
    "longitude": 153.0251,
    "zone": "Australia/Brisbane"
  },
  {
    "name": "Perth, Australia",
    "latitude": -31.9505,
    "longitude": 115.8605,
    "zone": "Australia/Perth"
  },
  {
    "name": "Adelaide, Australia",
    "latitude": -34.9285,
    "longitude": 138.6007,
    "zone": "Australia/Adelaide"
  },
  {
    "name": "Gold Coast, Australia",
    "latitude": -28.0167,
    "longitude": 153.4,
    "zone": "Australia/Brisbane"
  },
  {
    "name": "Canberra, Australia",
    "latitude": -35.2809,
    "longitude": 149.13,
    "zone": "Australia/Sydney"
  },
  {
    "name": "Hobart, Australia",
    "latitude": -42.8821,
    "longitude": 147.3272,
    "zone": "Australia/Hobart"
  },
  {
    "name": "Darwin, Australia",
    "latitude": -12.4634,
    "longitude": 130.8456,
    "zone": "Australia/Darwin"
  },
  {
    "name": "Auckland, New Zealand",
    "latitude": -36.8485,
    "longitude": 174.7633,
    "zone": "Pacific/Auckland"
  },
  {
    "name": "Wellington, New Zealand",
    "latitude": -41.2865,
    "longitude": 174.7762,
    "zone": "Pacific/Auckland"
  },
  {
    "name": "Christchurch, New Zealand",
    "latitude": -43.5321,
    "longitude": 172.6362,
    "zone": "Pacific/Auckland"
  },
  {
    "name": "Queenstown, New Zealand",
    "latitude": -45.0312,
    "longitude": 168.6626,
    "zone": "Pacific/Auckland"
  },
  {
    "name": "Toronto, Canada",
    "latitude": 43.651,
    "longitude": -79.347,
    "zone": "America/Toronto"
  },
  {
    "name": "Vancouver, Canada",
    "latitude": 49.2827,
    "longitude": -123.1207,
    "zone": "America/Vancouver"
  },
  {
    "name": "Montreal, Canada",
    "latitude": 45.5017,
    "longitude": -73.5673,
    "zone": "America/Toronto"
  },
  {
    "name": "Calgary, Canada",
    "latitude": 51.0447,
    "longitude": -114.0719,
    "zone": "America/Edmonton"
  },
  {
    "name": "Mexico City, Mexico",
    "latitude": 19.4326,
    "longitude": -99.1332,
    "zone": "America/Mexico_City"
  },
  {
    "name": "Guadalajara, Mexico",
    "latitude": 20.6597,
    "longitude": -103.3496,
    "zone": "America/Mexico_City"
  },
  {
    "name": "São Paulo, Brazil",
    "latitude": -23.5505,
    "longitude": -46.6333,
    "zone": "America/Sao_Paulo"
  },
  {
    "name": "Rio de Janeiro, Brazil",
    "latitude": -22.9068,
    "longitude": -43.1729,
    "zone": "America/Sao_Paulo"
  },
  {
    "name": "Buenos Aires, Argentina",
    "latitude": -34.6037,
    "longitude": -58.3816,
    "zone": "America/Argentina/Buenos_Aires"
  },
  {
    "name": "Santiago, Chile",
    "latitude": -33.4489,
    "longitude": -70.6693,
    "zone": "America/Santiago"
  },
  {
    "name": "Lima, Peru",
    "latitude": -12.0464,
    "longitude": -77.0428,
    "zone": "America/Lima"
  },
  {
    "name": "Bogotá, Colombia",
    "latitude": 4.711,
    "longitude": -74.0721,
    "zone": "America/Bogota"
  },
  {
    "name": "Cairo, Egypt",
    "latitude": 30.0444,
    "longitude": 31.2357,
    "zone": "Africa/Cairo"
  },
  {
    "name": "Cape Town, South Africa",
    "latitude": -33.9249,
    "longitude": 18.4241,
    "zone": "Africa/Johannesburg"
  },
  {
    "name": "Johannesburg, South Africa",
    "latitude": -26.2041,
    "longitude": 28.0473,
    "zone": "Africa/Johannesburg"
  },
  {
    "name": "Nairobi, Kenya",
    "latitude": -1.2921,
    "longitude": 36.8219,
    "zone": "Africa/Nairobi"
  },
  {
    "name": "Lagos, Nigeria",
    "latitude": 6.5244,
    "longitude": 3.3792,
    "zone": "Africa/Lagos"
  }
].map(Object.freeze));
