import fs from 'node:fs';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
const read = file => fs.readFileSync(new URL('../'+file, import.meta.url),'utf8');
const dom = new JSDOM(read('index.html'), {runScripts:'outside-only',url:'https://worldsystem.test/'});
const {window:win}=dom, doc=win.document;
win.ResizeObserver=class { observe(){} };
win.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
win.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new win.Event('close'));};
win.WorldSystemReady=true;
win.eval(read('locales/pl.js'));
win.eval(read('app-chrome.js'));
const settle=async()=>{for(let i=0;i<5;i++) await new Promise(r=>win.setTimeout(r,0));};
const modes=['explore','mandala','game','wheel','worlds','astrology'];
assert.deepEqual([...doc.querySelectorAll('[data-mode]')].map(x=>x.dataset.mode),modes);
assert.deepEqual([...doc.querySelectorAll('[data-intro-mode]')].map(x=>x.dataset.introMode),modes);
assert.match(doc.querySelector('#intro-title').textContent,/six/);
let about=0;doc.addEventListener('ws-about-open',()=>about++);
doc.querySelector('.app-brand').click();assert.equal(about,1);
assert.equal(doc.querySelector('.app-brand').tagName,'BUTTON');
const {createInterpretation}=await import('../interpretation-ui.js');
const entry=createInterpretation({doc,id:'lm_tha_skar'});doc.body.append(entry);
win.WorldSystemLocale.setLanguage('pl');await settle();
assert.equal(doc.querySelector('[data-mode=astrology] .t').textContent,'Astrologia');
assert.match(doc.querySelector('#intro-title').textContent,/sześć/);
assert.equal(doc.querySelector('.app-brand').title,'O modelu');
assert.match(entry.querySelector('.interpretation-language').textContent,/polskie tłumaczenie w przygotowaniu/);
assert.equal(entry.querySelector('[role=tab]').textContent,'Elekcyjna');
assert.match(entry.querySelector('summary').textContent,/Aśvinī — Source text pending/);
dom.window.close();
console.log('PASS: six menu/intro modes, brand About action, Polish chrome and explicit English interpretation notice.');
