import fs from 'node:fs';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
const read = file => fs.readFileSync(new URL('../'+file, import.meta.url),'utf8');
const dom = new JSDOM(read('index.html'), {runScripts:'outside-only',url:'https://worldsystem.test/'});
const {window:win}=dom, doc=win.document;
win.ResizeObserver=class { observe(){} };
win.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
win.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new win.Event('close'));};
win.WorldSystemReady=true;
win.eval(read('locales/pl.js'));
win.eval(read('app-chrome.js'));
const settle=async()=>{for(let i=0;i<5;i++) await new Promise(r=>win.setTimeout(r,0));};
const modes=['explore','mandala','game','wheel','worlds','astrology'];
assert.deepEqual([...doc.querySelectorAll('[data-mode]')].map(x=>x.dataset.mode),modes);
assert.deepEqual([...doc.querySelectorAll('[data-intro-mode]')].map(x=>x.dataset.introMode),modes);
assert.match(doc.querySelector('#intro-title').textContent,/six/);
assert.equal(doc.querySelector('[data-menu=mode] [data-start-tour]'),null);
const tour=doc.querySelector('[data-menu=options] [data-start-tour]');
assert.ok(tour);assert.equal(tour.parentElement.lastElementChild,tour);
let started=0;doc.addEventListener('ws-start-tour',()=>started++);
tour.click();assert.equal(started,1);
let about=0;doc.addEventListener('ws-about-open',()=>about++);
doc.querySelector('.app-brand').click();assert.equal(about,1);
assert.equal(doc.querySelector('.app-brand').tagName,'BUTTON');
const {createInterpretation}=await import('../interpretation-ui.js');
const entry=createInterpretation({doc,id:'lm_tha_skar'});doc.body.append(entry);
assert.equal(doc.querySelector('[data-language-flag]').textContent, '🇬🇧');
win.WorldSystemLocale.setLanguage('pl');await settle();
assert.equal(doc.querySelector('[data-language-flag]').textContent, '🇵🇱');
assert.equal(doc.querySelector('[data-mode=astrology] .t').textContent,'Astrologia');
assert.match(doc.querySelector('#intro-title').textContent,/sześć/);
assert.equal(doc.querySelector('.app-brand').title,'O modelu');
assert.match(entry.querySelector('.interpretation-references').textContent,/teksty interpretacji pozostają po angielsku/);
assert.match(entry.querySelector('.interpretation-references > summary').textContent,/Źródła i uwagi do przekładu/);
assert.equal(entry.querySelector('[role=tab]').textContent,'Działania');
assert.equal(entry.querySelector('summary > span').textContent,'Interpretacja');
assert.equal(entry.querySelector('.interpretation-expand').textContent,'Rozwiń');
assert.deepEqual([...entry.querySelectorAll('[role=tab]')].map(x=>x.textContent),['Działania','Narodziny','Połączenia','Rytuały']);
assert.equal(entry.querySelector('[role=tabpanel] li').textContent,'Teaching Dharma');
assert.match(entry.querySelector('summary').textContent,/Aśvinī/);
dom.window.close();
console.log('PASS: six menu/intro modes, brand About action, Polish interpretation chrome and preserved English readings.');
