// Form behaviour with a controlled provider; no ephemeris or network needed.
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createJyotishaPanel, PLACES } from '../jyotisha-panel.js';
import { YEAR_MIN, YEAR_MAX } from '../jyotisha.js';
const dom = new JSDOM('<div id="panel"></div>');
const doc = dom.window.document, panel = doc.querySelector('#panel');
let calls = 0, finish;
const ui = createJyotishaPanel({ doc, panel, now: () => Date.UTC(2025, 6, 1, 10),
  provider: { ready: true, calculate: () => { calls++; return new Promise(r => { finish = r; }); } } });
const form = panel.querySelector('form');
const edit = (name, value, type = 'input') => { const input = form.elements[name]; input.value = value; input.dispatchEvent(new dom.window.Event(type, {bubbles:true})); };
assert.equal(form.elements.date.min, YEAR_MIN + '-01-01');
assert.equal(form.elements.date.max, YEAR_MAX + '-12-31');
assert.deepEqual([...form.querySelectorAll(':scope > fieldset > legend')].map(x=>x.textContent), ['When','Where','Zone']);
assert.equal(PLACES.length,337);
assert.equal(panel.querySelector('.jy-coordinates').hidden,true);
edit('place','lodz');
assert.equal(panel.querySelector('[role=option]').textContent,'Łódź, Poland');
form.elements.place.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));
form.elements.place.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal(form.elements.latitude.value,'51.7592');
assert.equal(form.elements.longitude.value,'19.4558');
edit('place','Missing village');
assert.equal(form.elements.latitude.value,'','changing a selected city clears stale coordinates');
assert.equal(form.elements.zone.value,'','changing a city clears its zone');
assert.equal(panel.querySelector('[data-jy=manual]').hidden,false);
panel.querySelector('[data-jy=manual]').click();
assert.equal(panel.querySelector('.jy-coordinates').hidden,false);
edit('place','Krakow');
assert.equal(panel.querySelector('[data-jy=manual]').hidden,true);
assert.equal(panel.querySelector('[role=option]').textContent,'Kraków, Poland');
assert.equal(panel.querySelector('.jy-coordinates').hidden,true);
edit('place', 'Warsaw, Poland');
assert.equal(form.elements.latitude.value, '52.2297');
assert.equal(form.elements.zone.value, 'Europe/Warsaw');
panel.querySelector('[data-jy=now]').click();
assert.equal(form.elements.date.value, '2025-07-01');
assert.equal(form.elements.time.value, '12:00');
edit('date','2025-03-30'); edit('time','02:30');
await ui.submit();
assert.equal(calls,0);
assert.match(panel.querySelector('#jy-time-err').textContent,/does not occur/);
edit('date','2025-10-26');
await ui.submit();
assert.equal(calls,0);
assert.equal(panel.querySelector('.jy-choice').hidden,false);
panel.querySelector('[name=choice][value="1"]').click();
assert.equal(form.elements.choice.value,'1');
const pending = ui.submit();
assert.equal(calls,1);
edit('latitude','-33,8688');
finish({catalogueId:'lm_tha_skar'}); await pending;
assert.equal(ui.resultId,null,'an edited form cannot show a stale calculation');
assert.equal(panel.querySelector('[data-jy=show]').disabled,true);
edit('offset','+05:45'); form.elements.zoneMode.value='offset';
panel.querySelector('[data-jy=now]').click();
assert.equal(form.elements.time.value,'15:45');
edit('offset','invalid');
panel.querySelector('[data-jy=now]').click();
assert.equal(panel.querySelector('#jy-offset-err').hidden,false);
assert.equal(form.elements.latitude.value,'-33,8688','Use now preserves manual coordinates');
dom.window.close();
console.log('PASS: place presets, Use now, bounds, DST refusal/choice, manual coordinates and stale-result prevention.');
