// Source coordinates are copied verbatim; IANA zones are maintained separately.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const zones = JSON.parse(fs.readFileSync(path.join(root, 'data/city-zones.json'), 'utf8'));
function build() {
  let region = '';
  const places = [];
  for (const raw of fs.readFileSync(path.join(root, 'docs/Latitude: Longitude Cities.md'), 'utf8').split(/[\r\n\u2028\u2029]+/)) {
    const line = raw.trim(); if (!line) continue;
    if (!line.startsWith('•')) { region = line; continue; }
    const match = line.match(/^•\s*(.+?)\s*—\s*(-?\d+\.\d+),\s*(-?\d+\.\d+)$/);
    if (!match) throw Error('Malformed city: ' + line);
    const [, label, lat, lon] = match;
    const name = ['United States','Poland','India','Nepal','Bhutan','Taiwan','Thailand','China'].includes(region) ? `${label}, ${region}` : label;
    const zone = zones[name]; if (!zone) throw Error('Missing zone: ' + name);
    new Intl.DateTimeFormat('en', {timeZone: zone});
    const latitude = Number(lat), longitude = Number(lon);
    if (Math.abs(latitude)>90 || Math.abs(longitude)>180) throw Error('Invalid coordinates: '+name);
    places.push({name, latitude, longitude, zone});
  }
  if (new Set(places.map(p=>p.name)).size !== places.length) throw Error('Duplicate city');
  return '// Generated by scripts/build-places.cjs from the repository city list.\nexport const PLACES = Object.freeze(' + JSON.stringify(places, null, 2) + '.map(Object.freeze));\n';
}
module.exports = {build};
if (require.main === module) fs.writeFileSync(path.join(root,'places-data.js'),build());
